### ISSUE TITLE
Civil Protection VC ideas.

### ISSUE THREAD

**Issue by glob245** [Minerva-Servers/minervahl2rp-suggestions#11]
These voice command ideas for CPs may just be some misc stuff.

"You, hold it." yhold

"Spread your arms and legs, prepare for a search." search1

"Biotic, get to work." biotic1

"Biotic, I said get to work." biotic2

"Are you deaf?" deaf

"Stop talking." stoptalking

"Don't move, face the wall." dontmove1

"You have been charged with" chargedwith (cuts off because its meant to be used alongside one of the vcs that say for example "63 criminal tresspass)

"Come with me." come1

Thats all.

Pros : More voice commands for Civil Protection, and Riggs asked for some more.

Cons : Might sound a bit weird due to the AI.

**Comment by dasdhjuosdahusdahusdahdusahsdauoadsou** [comment]
+, don't question my name im breto

**Comment by riggs9162** [comment]
Send me your discord.
