### ISSUE TITLE
The Dropship Operator NPC 

### ISSUE THREAD

**Issue by haidarshahrizal** [Minerva-Servers/minervahl2rp-suggestions#4]
Hello! My name is John Jelaiu Johnson and I would to talk about the Dropship Operator NPC.
This NPC will let you deploy and your units to deploy in any sectors and zones. they'll be in the Nexus (or the Citadel). I will now be showing you the upsides and downsides of the Dropship Operator NPC. (And probably the Dropship itself)

_Upsides_
- Gives TFs or CPs access to a quick transportation to sectors and zones.
- The Dropship is a better option for a quick transportation 
- Lets you feel immersed with other units

_Downsides_
- Can only hold up to 6 units
- TFs can only deploy in a Dropship with a supervisor inside
- You will be vulnerable for a couple of seconds while landing
- Can only be used in Code Fractured or Void (unless it's special operations)

That's all I can suggest, I know it's not much but I hope it helps. -John Jelaiu Johnson

**Comment by riggs9162** [comment]
we have considered soldier dropship deployments, thank you for your input
