### ISSUE TITLE
OOC timer

### ISSUE THREAD

**Issue by Whovian321** [Minerva-Servers/minervahl2rp-suggestions#5]
Motherfucker
TWO WHOLE ASS MINUTES TO SEND A MESSAGE IN OOC, THATS WAY TOO LONG..

enough said

**Comment by Billy1011** [comment]
it was lowered not to long ago, i guess either redhart or riggs have put it to 2 minutes if riggs has put it to two minutes most likely wont be changed

**Comment by riggs9162** [comment]
redhart changed it to 60 seconds because i had put it to 1 second and i forgot to reset it back to 30 seconds, doesn't really matter because respawn times are different on the new hl2rp project.
